### ISSUE TITLE
Position of IPv4 space in code and in documentation

### ISSUE THREAD

**Issue by brigadier** [maxmind/MaxMind-DB#30]
Documentation:
`The strategy that MaxMind uses for its GeoIP databases is to include a 
pointer from the ::ffff:0:0/96 subnet to the root node of the IPv4 address 
space in the tree.`
Code of libraries use loop with `node = self._read_node(node, 0) ` - efectively `::0000:0:0/96`

Until the recent GeoIP2 Connection Type database, looking up IPv4 space at  `::ffff:0:0/96` worked fine, but now node 82 points to data instead of another node, so only `::0000:0:0/96` works now,

Can you comment on this? Is there anything I'm missing?

**Comment by oschwald** [comment]
The IPv4 space is inserted at `::/96`. Most databases distributed by MaxMind have several pointers to this data at other locations, including `::ffff:0:0/96`. It appears that this pointer is missing in the latest Connection-Type build. We are looking into that.

**Comment by oschwald** [comment]
The issue with the Connection-Type database, in particular, should be fixed in next week's release. That said, I would recommend updating https://github.com/brigadier/geodata2 to use `::/96` as the canonical location for IPv4 addresses, which should reduce the chance of issues in the future:

```
When storing IPv4 addresses in an IPv6 tree, they are stored as-is, so they occupy the first 32-bits of the address space (from 0 to 2**32 - 1).
```

`::ffff:0:0/96` is written out as an alias to `::/96`.

**Comment by brigadier** [comment]
Ok, thank you
